# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UosydMAkcg5IErEZxjbHE76xurcwOnVQY2zIkMrE+M5pwRPgCdEj7qIFEqLgMYSqgUMqrKeUvySU0sg+XH5BJ5B6vyRADzq+7aQ08rk3yvNpuI5+OaqREfKGOSxn5kkxpXlypV7ENpJN/v4R01DAvx1oJH5UF6NUXbhBHFG4/yGIwq+ooQAXCvNLySNp0eD+a/NKtDjbzkScZftJS4sAktPYq+0unnshl3h9eizcy6GTE/7v+s3A6uWsa/LN+/Jk0uE9blf9/V1RMaUQqnuQmCmxjK4f0qDAH8BRdocHgC/MkiC/1RIDcc/GK3UOu1pvzaab3DQDviBKgvDvWVHICYd0UjpN+m2ldkdojN61jRIY/r/fYkGgEYBq4MV6VplSPb77yD67NAFT8neJpWOr6UrkAbe5jCEtB1oNv/ZD69C3gtQVyWL+D5gg/Y6L75snQUCWISN6hXCwo0XyrVl9ic5NMAi41ph3Ds+1M4BTlQXw0PCGhveLgRHG/SH5g2JbXi8wgVhN/gsXTCZNDz2bE2RhWwREo37qOA/TZYjJpWJc2/BojLOzOpe1zggM8mL2Ok8t2D7osYce80F7AdcjiBIgsMla34uPvCyl/5YEvVlP/hh1XV9QjyTy+gPLYDaLH6TABRFx5LtTsSOtyWtfDUlPg5hR/W2bUc+lCaO/Vlc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
