travis:
  secure:
    BINSTAR_TOKEN: 7QeXIpbG5Avz5txlHUSqqMAO/8YsBoAqqM1fceZjFQC7i29aXtCNBGbLCu5zFlc+sZerRZ2UtC9RyL+Ns7HZtlYSecKROfO7dnf4UIWr52qEDpgR0BfCQJoCKQcXeCjbFrsVQs2PIRPcVigEf+0AkLIRh4urhA+azM8AUd/BZ1TzQqgj89n0fHFsrJtGMLt6SrhmkwMoQcJP4lEwEq9ysqfQ+NzaHusVAoRuYiJUSta9j/687vGKHC6wC0uY3D3h2QUme9OQOq6f81KGXjYYX13eHiXKfE57MTP1d8V2xd2ktlyFEfeSd0qi3uZM04CZ8CpQNpOBQZPb/9kWLBJbxAFxUvGmmYdchSBP/GYgza3xEobzE/SFWjjgOjBW8t6b+7oeWOMnFn644vBqWWARXKI6O3TwVoLm3DqqpN6RK01ThDFR0jWqCuEzHG7ZRrRFX9w/Sw6HpSJbjgO0vt/Fy04jyGyu1mhx5eaPvqofRJruyYzaDEWNpmig2jkvhtm2q9de9ed6sGkFmtATVlDn2HCaU/e1h7Ah3XZVshs/rNcL3wtBWhreQEbVTVYZYMO8HZMPgbqKg3rJcr3cVBC4M3d9WYKsW9qMwIXmiUADp8e/Hi8MtdjqTOiFVSy5HLKiC001VMjTaxh5aFQ+cVa+sNu18uu0cupeIvHBhWoEzxY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
